INVALID_USER_ID = 'INVALID_USER_ID'
ACCESS_DENIED = 'ACCESS_DENIED'

ACCOUNT_STATUS_PRIVATE = 'ACCOUNT_STATUS_PRIVATE'
ACCOUNT_STATUS_DELETED = 'ACCOUNT_STATUS_DELETED'
ACCOUNT_STATUS_BANNED = 'ACCOUNT_STATUS_BANNED'
ACCOUNT_STATUS_ABSENT = 'ACCOUNT_STATUS_ABSENT'
ACCOUNT_STATUS_PUBLIC = 'ACCOUNT_STATUS_PUBLIC'
ACCOUNT_STATUS_VALID = 'ACCOUNT_STATUS_VALID'
