QUERY_RESULT_ERROR = 'QUERY_RESULT_ERROR'
QUERY_RESULT_INVALID_ID = 'QUERY_RESULT_INVALID_ID'
QUERY_RESULT_ACCESS_DENIED = 'QUERY_RESULT_ACCESS_DENIED'
QUERY_RESULT_PRIVATE_PROFILE = 'QUERY_RESULT_PRIVATE_PROFILE'


ACCOUNT_STATUS_PRIVATE = 'ACCOUNT_STATUS_PRIVATE'
ACCOUNT_STATUS_DELETED = 'ACCOUNT_STATUS_DELETED'
ACCOUNT_STATUS_BANNED = 'ACCOUNT_STATUS_BANNED'
ACCOUNT_STATUS_ABSENT = 'ACCOUNT_STATUS_ABSENT'
ACCOUNT_STATUS_PUBLIC = 'ACCOUNT_STATUS_PUBLIC'
ACCOUNT_STATUS_VALID = 'ACCOUNT_STATUS_VALID'

