

class AccountStatus:
    PRIVATE = 'ACCOUNT_STATUS_PRIVATE'
    DELETED = 'ACCOUNT_STATUS_DELETED'
    BANNED = 'ACCOUNT_STATUS_BANNED'
    ABSENT = 'ACCOUNT_STATUS_ABSENT'
    PUBLIC = 'ACCOUNT_STATUS_PUBLIC'
    VALID = 'ACCOUNT_STATUS_VALID'


class GroupStatus:
    ABSENT = 'GROUP_STATUS_ABSENT'
    VALID = 'GROUP_STATUS_VALID'
    DEACTIVATED = 'GROUP_STATUS_DEACTIVATED'


class CacheType:
    ONLY_WRITE = 1
    ONLY_READ = 2
    FULL_USE = 3
    IGNORE = 4


class PlotType:
    LINE = 'line'
    CIRCULAR = 'circular'
    HIST = 'hist'
