REQUEST_ERROR_404 = 'REQUEST_ERROR_404'

STATUS_GOOD_AGENT = 'STATUS_GOOD_AGENT'
STATUS_WAIT_AGENT = 'STATUS_WAIT_AGENT'
STATUS_DEAD_AGENT = 'STATUS_DEAD_AGENT'
STATUS_USING_AGENT = 'STATUS_USING_AGENT'

REQUEST_STATUS_OK = 'REQUEST_STATUS_OK'
REQUEST_STATUS_FAIL = 'REQUEST_STATUS_FAIL'
