version: "3.3"

volumes:
  db:

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db
