
ACCOUNT_STATUS_PRIVATE = 'ACCOUNT_STATUS_PRIVATE'
ACCOUNT_STATUS_DELETED = 'ACCOUNT_STATUS_DELETED'
ACCOUNT_STATUS_BANNED = 'ACCOUNT_STATUS_BANNED'
ACCOUNT_STATUS_ABSENT = 'ACCOUNT_STATUS_ABSENT'
ACCOUNT_STATUS_PUBLIC = 'ACCOUNT_STATUS_PUBLIC'
ACCOUNT_STATUS_VALID = 'ACCOUNT_STATUS_VALID'

GROUP_STATUS_ABSENT = 'GROUP_STATUS_ABSENT'
GROUP_STATUS_VALID = 'GROUP_STATUS_VALID'
GROUP_STATUS_DEACTIVATED = 'GROUP_STATUS_DEACTIVATED'

CACHE_TYPE_ONLY_WRITE = 1
CACHE_TYPE_ONLY_READ = 2
CACHE_TYPE_FULL_USE = 3
CACHE_TYPE_IGNORE = 4

PLOT_LINE = 'line'
PLOT_HIST = 'hist'
PLOT_CIRCULAR = 'circular'
