version: 1
formatters:
  default:
    format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout
loggers:
  vk:
    level: INFO
  cache:
    level: INFO
  session:
    level: ERROR
root:
  level: DEBUG
  handlers: [console]