VERSION: 1.0.1
BASE_URL: 'http://localhost:8000'
VK_APP:
  CLIENT_ID: 7898476
  SECRET: VOlOMVKWwkCMxP6PrEBQ

CACHING: true

# If "true" all loggers level sets to ERROR
# Rewrite in env_file

# DEBUG: true
vk:
  # 25 request in execute query, do not change!
  EXECUTE_QUERIES_BUNCH_COUNT: 25
  # TODO This is random value, must be specified
  EXECUTE_MAX_LENGTH: 15000

  rps:
    # RPS limit to each of token types
    # https://vk.com/dev/api_requests
    user: 3 # Can be increased to 5-7
    community: 3
    app: 5 # Can be increased to 20

logging:
  version: 1
  formatters:
    default:
      format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
  handlers:
    default:
      class: logging.StreamHandler
      level: DEBUG
      formatter: default
      stream: ext://sys.stdout
  loggers:
    '':
      level: DEBUG
    vk-layer:
      level: DEBUG
    vk:
      level: DEBUG
    debugger:
      level: DEBUG
    peewee:
      level: WARNING
    pymorphy2.opencorpora_dict:
      level: WARNING
  root:
    level: DEBUG
    handlers: [default]
    propagate: true

