version: "3.3"
volumes:
    postgres:
    redis:

services:
  api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - env_file

  redis:
    build: redis
    restart: always
    volumes:
      - redis:/usr/local/etc/redis
    ports:
      - "6379:6379"


#  postgres:
#    image: postgres
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#      PGDATA: /data/postgres
#
#    volumes:
#      - postgres:/data/postgres