version: "3.3"
volumes:
    postgres:
    redis:

services:
  api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      BASE_URL: http://0.0.0.0:8000


  redis:
    build: redis
    restart: always
    volumes:
      - redis:/usr/local/etc/redis
      - redis:/data
    ports:
      - "6379:6379"